/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as CoordenadasNumeroLinhaImport } from './routes/coordenadas.$numeroLinha'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CoordenadasNumeroLinhaRoute = CoordenadasNumeroLinhaImport.update({
  id: '/coordenadas/$numeroLinha',
  path: '/coordenadas/$numeroLinha',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/coordenadas/$numeroLinha': {
      id: '/coordenadas/$numeroLinha'
      path: '/coordenadas/$numeroLinha'
      fullPath: '/coordenadas/$numeroLinha'
      preLoaderRoute: typeof CoordenadasNumeroLinhaImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coordenadas/$numeroLinha': typeof CoordenadasNumeroLinhaRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coordenadas/$numeroLinha': typeof CoordenadasNumeroLinhaRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/coordenadas/$numeroLinha': typeof CoordenadasNumeroLinhaRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/coordenadas/$numeroLinha'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/coordenadas/$numeroLinha'
  id: '__root__' | '/' | '/coordenadas/$numeroLinha'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoordenadasNumeroLinhaRoute: typeof CoordenadasNumeroLinhaRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoordenadasNumeroLinhaRoute: CoordenadasNumeroLinhaRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/coordenadas/$numeroLinha"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/coordenadas/$numeroLinha": {
      "filePath": "coordenadas.$numeroLinha.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
