/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as NumeroLinhaSentidoImport } from './routes/$numeroLinha.$sentido'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const NumeroLinhaSentidoRoute = NumeroLinhaSentidoImport.update({
  id: '/$numeroLinha/$sentido',
  path: '/$numeroLinha/$sentido',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$numeroLinha/$sentido': {
      id: '/$numeroLinha/$sentido'
      path: '/$numeroLinha/$sentido'
      fullPath: '/$numeroLinha/$sentido'
      preLoaderRoute: typeof NumeroLinhaSentidoImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$numeroLinha/$sentido': typeof NumeroLinhaSentidoRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$numeroLinha/$sentido': typeof NumeroLinhaSentidoRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$numeroLinha/$sentido': typeof NumeroLinhaSentidoRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$numeroLinha/$sentido'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$numeroLinha/$sentido'
  id: '__root__' | '/' | '/$numeroLinha/$sentido'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NumeroLinhaSentidoRoute: typeof NumeroLinhaSentidoRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NumeroLinhaSentidoRoute: NumeroLinhaSentidoRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$numeroLinha/$sentido"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$numeroLinha/$sentido": {
      "filePath": "$numeroLinha.$sentido.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
